# Site settings
title: Knoxville Uechi-Ryu Karate School
email: knoxuechiryu@yahoo.com
hours: 10:00am - 11:00am
description: > # this means to ignore newlines until "baseurl:"
  Knoxville Uechi-Ryu Karate School currently holds class hours on Saturday from 10:00am - 11:00am at <a href="http://www.streetbeatzstudio.com/">Street Beatz Studio</a>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://okknoxville.com" # the base hostname & protocol for your site
school_phone: 413-822-5409

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F


# Social media
footer-links:
  facebook: okknoxville
  youtube: https://www.youtube.com/channel/UC7bI3ivdLrqV4BumMKY9scQ

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
